# Generated by Django 3.1.3 on 2021-05-13 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0006_auto_20200507_1449'),
        ('pybo', '0005_auto_20210513_1830'),
    ]

    operations = [
    ]
